import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { repoRoot } from "./repo-root.ts";

const tokens = readFileSync(join(repoRoot, "src/tokens.css"), "utf8");
const primitives = readFileSync(join(repoRoot, "src/primitives.css"), "utf8");
const bundle = readFileSync(join(repoRoot, "src/pc-ui.css"), "utf8");
const tokenDoc = readFileSync(join(repoRoot, ".agents/tokens.md"), "utf8");

/** Title-bar blue (`--pc-titlebar-bg`) as defined for each theme. */
const titlebarBlue = {
  light: "#1E5AA8",
  dark: "#2B6CB0",
} as const;

function customProperties(css: string): string[] {
  return [...css.matchAll(/(--pc-[a-z0-9-]+)\s*:/g)].map((match) => match[1]);
}

function definedTokens(css: string): Set<string> {
  return new Set(customProperties(css));
}

/** `--pc-*` names, including a trailing `*` prefix wildcard such as `--pc-font-size-*`. */
function tokenRefs(text: string): string[] {
  return [...text.matchAll(/--pc-[a-z0-9-]+\*?/g)].map((match) => match[0]);
}

function catalogTokens(markdown: string): string[] {
  const catalog = markdown.split("## Catalog")[1];
  expect(catalog, "tokens.md catalog section").toBeTruthy();
  return tokenRefs(catalog).filter((name) => !name.endsWith("*"));
}

function commentsOnly(source: string): string {
  const blocks = [...source.matchAll(/\/\*[\s\S]*?\*\//g)].map((match) => match[0]);
  const lines = [...source.matchAll(/(^|[^:])\/\/(.*)$/gm)].map((match) => match[2]);
  return [...blocks, ...lines].join("\n");
}

function walk(dir: string, acc: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) walk(path, acc);
    else acc.push(path);
  }
  return acc;
}

function expectKnownToken(name: string, defined: Set<string>): void {
  if (name.endsWith("*")) {
    const prefix = name.slice(0, -1);
    const matches = [...defined].filter((token) => token.startsWith(prefix));
    expect(matches, name).not.toEqual([]);
    return;
  }
  expect(defined.has(name), name).toBe(true);
}

function assignment(css: string, header: string, name: string): string {
  const start = css.indexOf(header);
  expect(start, header).toBeGreaterThanOrEqual(0);
  const slice = css.slice(start);
  const match = slice.match(new RegExp(`${name}\\s*:\\s*([^;]+);`));
  expect(match, `${header} ${name}`).toBeTruthy();
  return match![1].trim();
}

const themeSelectors = [
  ".pc-theme-light",
  ".pc-theme-dark",
  ".pc-theme-system",
  '[data-pc-theme="light"]',
  '[data-pc-theme="dark"]',
  '[data-pc-theme="system"]',
];

const docFiles = ["README.md", "AGENTS.md", ".agents/tokens.md", ".agents/testing.md"];

describe("CSS tokens", () => {
  it("matches the documented catalog to every token in tokens.css", () => {
    const defined = [...definedTokens(tokens)].sort();
    const catalog = catalogTokens(tokenDoc);
    expect(catalog).toEqual([...new Set(catalog)]);
    expect([...catalog].sort()).toEqual(defined);
  });

  it("only cites real token names from docs and comments", () => {
    const defined = definedTokens(tokens);
    const sources = [
      ...docFiles.map((file) => readFileSync(join(repoRoot, file), "utf8")),
      ...walk(join(repoRoot, "src"))
        .filter((file) => /\.(css|ts|tsx)$/.test(file) && !file.endsWith("pc-ui.css"))
        .map((file) => commentsOnly(readFileSync(file, "utf8"))),
      ...walk(join(repoRoot, "test")).map((file) => readFileSync(file, "utf8")),
      ...walk(join(repoRoot, "scripts")).map((file) => commentsOnly(readFileSync(file, "utf8"))),
    ];

    for (const name of sources.flatMap(tokenRefs)) {
      expectKnownToken(name, defined);
    }
  });

  it("documents the title-bar blue on --pc-titlebar-bg", () => {
    expect(assignment(tokens, ":root", "--pc-titlebar-bg").toLowerCase()).toBe(
      titlebarBlue.light.toLowerCase()
    );
    expect(assignment(tokens, ".pc-theme-dark", "--pc-titlebar-bg").toLowerCase()).toBe(
      titlebarBlue.dark.toLowerCase()
    );
    expect(assignment(tokens, ".pc-theme-system", "--pc-titlebar-bg").toLowerCase()).toBe(
      titlebarBlue.dark.toLowerCase()
    );

    for (const file of ["README.md", "AGENTS.md", ".agents/tokens.md"]) {
      const text = readFileSync(join(repoRoot, file), "utf8");
      expect(text, file).toContain("--pc-titlebar-bg");
      expect(text, file).toContain(titlebarBlue.light);
      expect(text, file).toContain(titlebarBlue.dark);
    }
  });

  it("defines light, dark, and system theme selectors", () => {
    for (const selector of themeSelectors) {
      expect(tokens, selector).toContain(selector);
    }
  });

  it("keeps the generated bundle in sync with tokens and primitives", () => {
    expect(primitives).toContain('@import "./tokens.css"');
    expect(bundle).not.toContain('@import "./tokens.css"');
    expect(bundle).toContain("Generated by scripts/bundle-css.mjs");

    const tokenProps = new Set(customProperties(tokens));
    const bundleProps = new Set(customProperties(bundle));
    const missing = [...tokenProps].filter((name) => !bundleProps.has(name));
    expect(missing).toEqual([]);

    for (const className of [
      ".pc-button",
      ".pc-window",
      ".pc-desktop",
      ".pc-taskbar",
      ".pc-overflow-menu",
      ".pc-window--freeform",
    ]) {
      expect(primitives, className).toContain(className);
      expect(bundle, className).toContain(className);
    }
  });
});
