import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { repoRoot } from "./repo-root.ts";

const tokens = readFileSync(join(repoRoot, "src/tokens.css"), "utf8");
const primitives = readFileSync(join(repoRoot, "src/primitives.css"), "utf8");
const bundle = readFileSync(join(repoRoot, "src/pc-ui.css"), "utf8");

/** Public custom properties documented for theming. */
const publicTokens = [
  "--pc-desktop-bg",
  "--pc-chrome-bg",
  "--pc-chrome-dark",
  "--pc-window-body-bg",
  "--pc-titlebar-bg",
  "--pc-titlebar-text",
  "--pc-terminal-bg",
  "--pc-terminal-titlebar",
  "--pc-terminal-text",
  "--pc-text-main",
  "--pc-text-muted",
  "--pc-link",
  "--pc-link-visited",
  "--pc-link-active",
  "--pc-color-error",
  "--pc-color-error-bg",
  "--pc-color-warning",
  "--pc-color-warning-bg",
  "--pc-color-success",
  "--pc-color-success-bg",
  "--pc-color-info",
  "--pc-color-info-bg",
  "--pc-button-hover-bg",
  "--pc-button-active-bg",
  "--pc-input-bg",
  "--pc-focus-ring",
  "--pc-focus-ring-offset",
  "--pc-bevel-light",
  "--pc-bevel-dark",
  "--pc-bevel-shadow",
  "--pc-bevel-inset-shadow",
  "--pc-font-family",
  "--pc-font-sans",
  "--pc-font-size-xs",
  "--pc-font-size-sm",
  "--pc-font-size-md",
  "--pc-line-height-tight",
  "--pc-line-height-body",
  "--pc-space-1",
  "--pc-space-2",
  "--pc-space-3",
  "--pc-space-4",
  "--pc-space-5",
  "--pc-tile-gap",
  "--pc-tile-grow",
  "--pc-overlay-bg",
  "--pc-overlay-z",
  "--pc-toast-z",
  "--pc-toast-offset-x",
  "--pc-toast-offset-y",
];

const themeSelectors = [
  ".pc-theme-light",
  ".pc-theme-dark",
  ".pc-theme-system",
  '[data-pc-theme="light"]',
  '[data-pc-theme="dark"]',
  '[data-pc-theme="system"]',
];

function customProperties(css: string): string[] {
  return [...css.matchAll(/(--pc-[a-z0-9-]+)\s*:/g)].map((match) => match[1]);
}

describe("CSS tokens", () => {
  it("defines the documented token names", () => {
    for (const name of publicTokens) {
      expect(tokens, name).toContain(`${name}:`);
    }
  });

  it("defines light, dark, and system theme selectors", () => {
    for (const selector of themeSelectors) {
      expect(tokens, selector).toContain(selector);
    }
  });

  it("keeps the generated bundle in sync with tokens and primitives", () => {
    expect(primitives).toContain('@import "./tokens.css"');
    expect(bundle).not.toContain('@import "./tokens.css"');
    expect(bundle).toContain("Generated by scripts/bundle-css.mjs");

    const tokenProps = new Set(customProperties(tokens));
    const bundleProps = new Set(customProperties(bundle));
    const missing = [...tokenProps].filter((name) => !bundleProps.has(name));
    expect(missing).toEqual([]);

    for (const className of [".pc-button", ".pc-window", ".pc-desktop", ".pc-taskbar"]) {
      expect(primitives, className).toContain(className);
      expect(bundle, className).toContain(className);
    }
  });
});
